# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Run1Gibbs_cpp <- function(ninst, Y, X1, hp_mu_coef, hp_a, hp_b, hp_g_coef, hp_sig2_y, hp_pi, hp_inv_Sig_coef, coef, sig2_error, delta) {
    .Call('_BayesianMIR_Run1Gibbs_cpp', PACKAGE = 'BayesianMIR', ninst, Y, X1, hp_mu_coef, hp_a, hp_b, hp_g_coef, hp_sig2_y, hp_pi, hp_inv_Sig_coef, coef, sig2_error, delta)
}

BMIR_cpp <- function(ntotal, nwarm, nthin, ninst, Y, X1, hp_mu_coef, hp_a, hp_b, hp_g_coef, hp_sig2_y, hp_pi, hp_inv_Sig_coef, coef, sig2_error, delta, return_delta = FALSE) {
    .Call('_BayesianMIR_BMIR_cpp', PACKAGE = 'BayesianMIR', ntotal, nwarm, nthin, ninst, Y, X1, hp_mu_coef, hp_a, hp_b, hp_g_coef, hp_sig2_y, hp_pi, hp_inv_Sig_coef, coef, sig2_error, delta, return_delta)
}

